id: task-2
available: true
type: 2
wait_seconds: 1
kompose:
  items:
    - docker_compose_content: |
        version: "3"

        services:
          redis:
            image: redis:3.1
            ports:
              - "6379"
