id: task-2
available: true
wait_seconds: 1
convert_to_k8s: true
kompose:
  items:
    - docker_compose_content: |
        version: "3"
        services:
          web:
            image: wordpress:4.5
            ports:
              - '80'
            environment:
              WORDPRESS_AUTH_KEY: changeme
              WORDPRESS_SECURE_AUTH_KEY: changeme
              WORDPRESS_LOGGED_IN_KEY: changeme
              WORDPRESS_NONCE_KEY: changeme
              WORDPRESS_AUTH_SALT: changeme
              WORDPRESS_SECURE_AUTH_SALT: changeme
              WORDPRESS_LOGGED_IN_SALT: changeme
              WORDPRESS_NONCE_SALT: changeme
              WORDPRESS_NONCE_AA: changeme
            restart: always
            links:
              - 'db:mysql'
          db:
            image: mysql:5.7
            environment:
              MYSQL_ROOT_PASSWORD: password
            restart: always
            labels:
              project.logs: /var/log/mysql
              kompose.controller.type: daemonset
    - docker_compose_content: |
        version: "3"

        services:

        web:
          image: tuna/docker-counter23
          ports:
            - "5000:5000"
          deploy:
            replicas: 1
            restart_policy:
              condition: any
          labels:
            kompose.service.type: NodePort

        redis:
          image: redis:3.0
          ports:
            - "6379"
