apiVersion: v1
clusters:
- cluster:
    certificate-authority: C:\Users\luoru\.minikube\ca.crt
    extensions:
    - extension:
        last-update: Tue, 01 Aug 2023 15:38:56 CST
        provider: minikube.sigs.k8s.io
        version: v1.30.1
      name: cluster_info
    server: https://127.0.0.1:37610
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Tue, 01 Aug 2023 15:38:56 CST
        provider: minikube.sigs.k8s.io
        version: v1.30.1
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: C:\Users\luoru\.minikube\profiles\minikube\client.crt
    client-key: C:\Users\luoru\.minikube\profiles\minikube\client.key
